### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by christian-korneck** [aadog/py3-go#1]
thanks for this interesting project, I'm about to start playing with it. Is there any chance that you could add a `LICENSE` file (or clarify the license in some other way)? Thanks!!

**Comment by aadog** [comment]
https://github.com/go-python/cpy3/issues/22#issuecomment-1215430870

already replied

**Comment by abemedia** [comment]
Would be good to add a license file anyway so we can have docs: https://pkg.go.dev/github.com/aadog/py3-go

**Comment by aadog** [comment]
license added
